---
- hosts: localhost
  connection: local
  gather_facts: no
  remote_user: root
  vars_files:
    - vault.yml

  tasks:

    - name: Create a virtual machine from a template
      vmware_guest:
        hostname: "{{ vc_name }}"
        username: "{{ myuser }}"
        password: "{{ mypass }}"
        validate_certs: no
        folder: /Ansible/ansible-staging
        name: testvm_1
        state: poweredon
        template: RedHat
        datacenter: homelab
        disk:
        - size_gb: 16
          type: thin
          datastore: naboo
        hardware:
          memory_mb: 1024
          num_cpus: 1
          num_cpu_cores_per_socket: 1
          scsi: paravirtual
          hotadd_cpu: True
          hotremove_cpu: True
          hotadd_memory: False
          version: 12
          boot_firmware: "efi"
        networks:
        - name: homelab network
          type: dhcp
          device_type: vmxnet3
          start_connected: True
        customization:
          dns_servers:
            - 172.30.1.252
            - 1.1.1.1
          dns_suffix:
            - testvm_1.kingdom.local
          hostname: testvm_1
        wait_for_ip_address: yes
      delegate_to: localhost
      register: deploy
