---
- hosts: localhost
  connection: local
  gather_facts: no
  remote_user: root
  vars_files:
    - vault.yml

  tasks:

    - name: Create a virtual machine on given ESXi hostname
      vmware_guest:
        hostname: "{{ vc_name }}"
        username: "{{ myuser }}"
        password: "{{ mypass }}"
        folder: /
        validate_certs: no
        name: Hoobastank01
        state: poweredon
        guest_id: centos64Guest
        esxi_hostname: "{{ vc_name }}"
        disk:
        - size_gb: 10
          type: thin
          datastore: r2d2
        hardware:
          memory_mb: 512
          num_cpus: 4
          scsi: paravirtual
        cdrom:
          type: iso
          iso_path: "[c3po] iso/centos.iso"
        networks:
        - name: homelab network
          mac: aa:bb:dd:aa:00:14
          ip: 172.30.1.201
          netmask: 255.255.255.0
          device_type: vmxnet3
        wait_for_ip_address: yes
        validate_certs: no
      delegate_to: localhost
      register: deploy_vm
